# -*- coding: utf-8 -*-
"""5243HW2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16SOC-Kda3b8-HOZ029VfT3_eEb9RsOAP
"""

import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
from itertools import combinations

def generate_candidates_fk_fk(frequent_k_minus_1):
    candidates = []
    f_list = sorted(list(frequent_k_minus_1))
    length = len(f_list)
    for i in range(length):
        for j in range(i + 1, length):
            l1, l2 = f_list[i], f_list[j]
            if l1[:-1] == l2[:-1]:
                candidate = tuple(sorted(set(l1) | set(l2)))
                candidates.append(candidate)
    return candidates

def generate_candidates_fk_f1(frequent_k_minus_1, frequent_1):
    candidates = set()
    for itemset in frequent_k_minus_1:
        for f1_item in frequent_1:
            new_item = f1_item[0]
            if new_item not in itemset:
                candidate = tuple(sorted(itemset + (new_item,)))
                candidates.add(candidate)
    return list(candidates)

def get_frequent_itemsets(candidates, sparse_matrix, min_support_count):
    if not candidates: return {}, []
    frequent_counts = {}
    frequent_itemsets = []
    for cand in candidates:
        cols = list(cand)
        support = (sparse_matrix[:, cols].sum(axis=1) == len(cols)).sum()
        if support >= min_support_count:
            frequent_itemsets.append(cand)
            frequent_counts[cand] = support
    return frequent_counts, frequent_itemsets

def get_subsets(itemset):
    subsets = []
    for i in range(1, len(itemset)):
        subsets.extend(combinations(itemset, i))
    return [tuple(sorted(s)) for s in subsets]

def generate_association_rules(frequent_counts, num_transactions, min_conf):
    rules = []
    for itemset, support_count in frequent_counts.items():
        if len(itemset) > 1:
            for A in get_subsets(itemset):
                B = tuple(sorted(set(itemset) - set(A)))

                if A in frequent_counts and B in frequent_counts:
                    supp_A = frequent_counts[A] / num_transactions
                    supp_B = frequent_counts[B] / num_transactions
                    supp_AB = support_count / num_transactions

                    conf = supp_AB / supp_A
                    if conf >= min_conf:
                        lift = conf / supp_B
                        rules.append({
                            'antecedent': A,
                            'consequent': B,
                            'confidence': conf,
                            'lift': lift
                        })
    return sorted(rules, key=lambda x: x['lift'], reverse=True)

def format_rule(rule, col_names):
    ant = ", ".join([col_names[i] for i in rule['antecedent']])
    con = ", ".join([col_names[i] for i in rule['consequent']])
    return f"{{{ant}}} -> {{{con}}}"

def preprocess_dataset(name, path):
    print(f"\nPreprocessing {name}...")
    if name == "Car":
        df = pd.read_csv(path, names=['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'])
        features = df.drop(columns=['class'])
    elif name == "Communities":
        df = pd.read_csv(path, header=None, na_values='?')
        df = df.iloc[:, 5:20].dropna(axis=1, thresh=len(df)*0.8)
        features = df.fillna(df.mean())
    elif name == "CreditCard":
        df = pd.read_excel(path, header=1)
        features = df.iloc[:, 1:11]

    for col in features.columns:
        if features[col].dtype in [np.float64, np.int64] and features[col].nunique() > 5:
            features[col] = pd.qcut(features[col], 3, labels=False, duplicates='drop')

    binary_df = pd.get_dummies(features, prefix_sep='=', columns=features.columns)
    return csr_matrix(binary_df.values), list(binary_df.columns), len(features)

def run_dataset(name, sparse_matrix, col_names, num_transactions, base_support, conf_levels):
    print(f"\n{'='*80}\nDataset: {name} | Min Support: {base_support*100}%")
    min_support_count = int(base_support * num_transactions)
    all_frequent_counts = {}
    f1_candidates = [tuple([i]) for i in range(sparse_matrix.shape[1])]

    f1_counts, current_f = get_frequent_itemsets(f1_candidates, sparse_matrix, min_support_count)
    all_frequent_counts.update(f1_counts)
    k = 2
    while current_f and k <= 4:
        c_fk_fk = generate_candidates_fk_fk(current_f)
        next_counts, next_f = get_frequent_itemsets(c_fk_fk, sparse_matrix, min_support_count)
        all_frequent_counts.update(next_counts)
        current_f = next_f
        k += 1

    print(f"Total Frequent Itemsets Mined: {len(all_frequent_counts)}")
    for conf in conf_levels:
        rules = generate_association_rules(all_frequent_counts, num_transactions, conf)
        print(f"\n  --- Min Confidence: {conf*100}% ---")
        print(f"  Total Rules Generated: {len(rules)}")
        print(f"  Top 10 Rules (Sorted by Lift):")
        for i, r in enumerate(rules[:10]):
            rule_str = format_rule(r, col_names)
            print(f"    {i+1}. {rule_str}")
            print(f"       Conf: {r['confidence']:.3f} | Lift: {r['lift']:.3f}")

datasets_info = [
    ("Car", 'car.data', 0.1, [0.5, 0.7, 0.9]),
    ("Communities", 'communities.data', 0.25, [0.5, 0.7, 0.9]),
    ("CreditCard", 'default of credit card clients.xls', 0.25, [0.5, 0.7, 0.9])
]

for name, path, base_sup, conf_levels in datasets_info:
    sparse_mat, cols, n_rows = preprocess_dataset(name, path)
    run_dataset(name, sparse_mat, cols, n_rows, base_sup, conf_levels)

import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix
from itertools import combinations

def generate_candidates_fk_fk(frequent_k_minus_1):
    candidates = []
    f_list = sorted(list(frequent_k_minus_1))
    length = len(f_list)
    for i in range(length):
        for j in range(i + 1, length):
            l1, l2 = f_list[i], f_list[j]
            if l1[:-1] == l2[:-1]:
                candidate = tuple(sorted(set(l1) | set(l2)))
                candidates.append(candidate)
    return candidates

def generate_candidates_fk_f1(frequent_k_minus_1, frequent_1):
    candidates = set()
    for itemset in frequent_k_minus_1:
        for f1_item in frequent_1:
            new_item = f1_item[0]
            if new_item not in itemset:
                candidate = tuple(sorted(itemset + (new_item,)))
                candidates.add(candidate)
    return list(candidates)

def get_frequent_itemsets(candidates, sparse_matrix, min_support_count):
    if not candidates: return {}, []
    frequent_counts = {}
    frequent_itemsets = []
    for cand in candidates:
        cols = list(cand)
        support = (sparse_matrix[:, cols].sum(axis=1) == len(cols)).sum()
        if support >= min_support_count:
            frequent_itemsets.append(cand)
            frequent_counts[cand] = support
    return frequent_counts, frequent_itemsets

def get_subsets(itemset):
    subsets = []
    for i in range(1, len(itemset)):
        subsets.extend(combinations(itemset, i))
    return [tuple(sorted(s)) for s in subsets]

def generate_association_rules(frequent_counts, num_transactions, min_conf):
    rules = []
    for itemset, support_count in frequent_counts.items():
        if len(itemset) > 1:
            for A in get_subsets(itemset):
                B = tuple(sorted(set(itemset) - set(A)))

                if A in frequent_counts and B in frequent_counts:
                    supp_A = frequent_counts[A] / num_transactions
                    supp_B = frequent_counts[B] / num_transactions
                    supp_AB = support_count / num_transactions

                    conf = supp_AB / supp_A
                    if conf >= min_conf:
                        lift = conf / supp_B
                        rules.append({
                            'antecedent': A,
                            'consequent': B,
                            'confidence': conf,
                            'lift': lift
                        })
    return sorted(rules, key=lambda x: x['lift'], reverse=True)

def format_rule(rule, col_names):
    ant = ", ".join([col_names[i] for i in rule['antecedent']])
    con = ", ".join([col_names[i] for i in rule['consequent']])
    return f"{{{ant}}} -> {{{con}}}"

def preprocess_dataset(name, path):
    print(f"\nPreprocessing {name}...")
    if name == "Car":
        df = pd.read_csv(path, names=['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'])
        features = df.drop(columns=['class'])
    elif name == "Communities":
        df = pd.read_csv(path, header=None, na_values='?')
        df = df.iloc[:, 5:20].dropna(axis=1, thresh=len(df)*0.8)
        features = df.fillna(df.mean())
    elif name == "CreditCard":
        df = pd.read_excel(path, header=1)
        features = df.iloc[:, 1:11]

    for col in features.columns:
        if features[col].dtype in [np.float64, np.int64] and features[col].nunique() > 5:
            features[col] = pd.qcut(features[col], 3, labels=False, duplicates='drop')

    binary_df = pd.get_dummies(features, prefix_sep='=', columns=features.columns)
    return csr_matrix(binary_df.values), list(binary_df.columns), len(features)

def run_dataset(name, sparse_matrix, col_names, num_transactions, base_support, conf_levels):
    print(f"\n{'='*80}\nDataset: {name} | Min Support: {base_support*100}%")
    min_support_count = int(base_support * num_transactions)
    all_frequent_counts = {}
    f1_candidates = [tuple([i]) for i in range(sparse_matrix.shape[1])]

    f1_counts, f1_frequent = get_frequent_itemsets(f1_candidates, sparse_matrix, min_support_count)
    all_frequent_counts.update(f1_counts)

    print(f"{'Level k':<10} | {'Fk-1 x F1 Cands':<18} | {'Fk-1 x Fk-1 Cands':<18} | {'Frequent Sets'}")
    print("-" * 70)

    current_f = f1_frequent
    k = 2
    while current_f and k <= 4:
        c_fk_f1 = generate_candidates_fk_f1(current_f, f1_frequent)
        c_fk_fk = generate_candidates_fk_fk(current_f)
        next_counts, next_f = get_frequent_itemsets(c_fk_fk, sparse_matrix, min_support_count)
        all_frequent_counts.update(next_counts)

        print(f"{k:<10} | {len(c_fk_f1):<18} | {len(c_fk_fk):<18} | {len(next_f)}")

        current_f = next_f
        k += 1

    print(f"\nTotal Frequent Itemsets Mined: {len(all_frequent_counts)}")
    for conf in conf_levels:
        rules = generate_association_rules(all_frequent_counts, num_transactions, conf)
        print(f"\n  --- Min Confidence: {conf*100}% ---")
        print(f"  Total Rules Generated: {len(rules)}")
        print(f"  Top 10 Rules (Sorted by Lift):")
        for i, r in enumerate(rules[:10]):
            rule_str = format_rule(r, col_names)
            print(f"    {i+1}. {rule_str}")
            print(f"       Conf: {r['confidence']:.3f} | Lift: {r['lift']:.3f}")

datasets_info = [
    ("Car", 'car.data', 0.1, [0.5, 0.7, 0.9]),
    ("Communities", 'communities.data', 0.25, [0.5, 0.7, 0.9]),
    ("CreditCard", 'default of credit card clients.xls', 0.25, [0.5, 0.7, 0.9])
]

for name, path, base_sup, conf_levels in datasets_info:
    sparse_mat, cols, n_rows = preprocess_dataset(name, path)
    run_dataset(name, sparse_mat, cols, n_rows, base_sup, conf_levels)